//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forsaj.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int saleID { get; set; }
        public int abonementID { get; set; }
        public int clientID { get; set; }
        public System.DateTime saleDate { get; set; }
        public System.TimeSpan saleTime { get; set; }
    
        public virtual Abonements Abonements { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
