//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forsaj.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int trainingID { get; set; }
        public int trainerID { get; set; }
        public int dayID { get; set; }
        public string trainingTimeStart { get; set; }
        public System.DateTime trainingDate { get; set; }
        public string trainingDescription { get; set; }
    
        public virtual Days Days { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
