//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forsaj.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int staffID { get; set; }
        public int roleID { get; set; }
        public string staffName { get; set; }
        public string staffSurname { get; set; }
        public string staffPatronymic { get; set; }
        public string staffLogin { get; set; }
        public string staffPassword { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
