//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forsaj.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitHistory
    {
        public int visitID { get; set; }
        public int clientID { get; set; }
        public System.TimeSpan visitTime { get; set; }
        public System.DateTime visitDate { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
